In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]

In [5]:
arr=np.array(my_list)

In [6]:
arr.shape

(3,)

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix[2]

[7, 8, 9]

In [9]:
arr=np.array(my_matrix)

In [10]:
arr.shape

(3, 3)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr=np.arange(0,10)

In [16]:
arr.shape

(10,)

In [19]:
arr.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [28]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [31]:
np.linspace(0,10)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [32]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [38]:
np.random.rand(5,5)

array([[ 0.94251827,  0.44263323,  0.28654548,  0.50398272,  0.35307217],
       [ 0.35659522,  0.21457201,  0.54873259,  0.99398781,  0.36462335],
       [ 0.29522612,  0.07002931,  0.32291099,  0.69206725,  0.79732873],
       [ 0.65247457,  0.89105225,  0.19785745,  0.19974799,  0.29431832],
       [ 0.45605094,  0.91931009,  0.6164832 ,  0.72421457,  0.99718321]])

In [42]:
np.random.randn(5,5)

array([[ 0.23705241,  0.14704   , -0.49096978,  2.05465807,  0.18317377],
       [-1.2295528 , -0.67241589,  0.10987121,  0.16205333, -0.27425889],
       [-0.875135  , -1.04804277, -0.55197778, -1.66579585, -0.18881407],
       [ 1.7879989 ,  1.16072623,  2.22806065, -1.73989261, -0.98125517],
       [ 0.81685086,  0.25930633, -0.45662709,  0.66704476, -0.45422117]])

In [47]:
arr=np.random.randint(1,100,10)

In [50]:
arr

array([27, 36, 69, 36, 72, 22, 22, 52, 60, 29])

In [48]:
arr.max()

72

In [49]:
arr.min()

22

In [52]:
arr.argmin()

5

In [69]:
arr = np.arange(0,10)

In [62]:
arr=arr.reshape(5,2)

In [64]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr[0:5]=100

In [73]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [74]:
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [76]:
slice_of_arr[:]=100

In [77]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [78]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [79]:
arr_copy = arr.copy()

In [80]:
arr_copy[:]=600

In [81]:
arr_copy

array([600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600])

In [82]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [84]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [90]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [91]:
arr_2d[:,2:]

array([[15],
       [30],
       [45]])

In [95]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [96]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [98]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [99]:
arr/arr

C:\Users\krish.naik\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [100]:
1/arr

C:\Users\krish.naik\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [101]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [102]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [104]:
import pandas as pd

In [107]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [108]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [109]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [111]:
pd.Series(d,['b','c','d'])

b    20.0
c    30.0
d     NaN
dtype: float64

In [112]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [113]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])  

In [114]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])  

In [115]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [119]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [120]:
df

W         X         Y         Z
A -1.534740  1.060125  0.044443 -0.528856
B -0.087593  0.919276 -0.073113  0.294783
C -2.023998 -1.549054  0.268636  1.020451
D -1.457864 -0.038593  1.641223 -0.479749
E -1.434301 -1.385836 -0.031115 -1.088052

In [125]:
df[['W','X']]

W         X
A -1.534740  1.060125
B -0.087593  0.919276
C -2.023998 -1.549054
D -1.457864 -0.038593
E -1.434301 -1.385836

In [126]:
df.W

A   -1.534740
B   -0.087593
C   -2.023998
D   -1.457864
E   -1.434301
Name: W, dtype: float64

In [127]:
df['new'] = df['W'] + df['Y']

In [128]:
df

W         X         Y         Z       new
A -1.534740  1.060125  0.044443 -0.528856 -1.490298
B -0.087593  0.919276 -0.073113  0.294783 -0.160705
C -2.023998 -1.549054  0.268636  1.020451 -1.755362
D -1.457864 -0.038593  1.641223 -0.479749  0.183359
E -1.434301 -1.385836 -0.031115 -1.088052 -1.465416

In [131]:
df.drop('new',axis=1,inplace=True)

In [132]:
df

W         X         Y         Z
A -1.534740  1.060125  0.044443 -0.528856
B -0.087593  0.919276 -0.073113  0.294783
C -2.023998 -1.549054  0.268636  1.020451
D -1.457864 -0.038593  1.641223 -0.479749
E -1.434301 -1.385836 -0.031115 -1.088052

In [139]:
df.loc[['A','B'],['W','X']]

W         X
A -1.534740  1.060125
B -0.087593  0.919276

In [137]:
df.iloc[2:,[0,3]]

W         Z
C -2.023998  1.020451
D -1.457864 -0.479749
E -1.434301 -1.088052

In [140]:
df

W         X         Y         Z
A -1.534740  1.060125  0.044443 -0.528856
B -0.087593  0.919276 -0.073113  0.294783
C -2.023998 -1.549054  0.268636  1.020451
D -1.457864 -0.038593  1.641223 -0.479749
E -1.434301 -1.385836 -0.031115 -1.088052

In [145]:
df[df['X']>0]

W         X         Y         Z
A -1.534740  1.060125  0.044443 -0.528856
B -0.087593  0.919276 -0.073113  0.294783

In [146]:
df[df['W']>0]['Y']

Series([], Name: Y, dtype: float64)

In [147]:
df[(df['Z']>0) & (df['Y'] > 1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [148]:
df

W         X         Y         Z
A -1.534740  1.060125  0.044443 -0.528856
B -0.087593  0.919276 -0.073113  0.294783
C -2.023998 -1.549054  0.268636  1.020451
D -1.457864 -0.038593  1.641223 -0.479749
E -1.434301 -1.385836 -0.031115 -1.088052

In [149]:
df.reset_index()

index         W         X         Y         Z
0     A -1.534740  1.060125  0.044443 -0.528856
1     B -0.087593  0.919276 -0.073113  0.294783
2     C -2.023998 -1.549054  0.268636  1.020451
3     D -1.457864 -0.038593  1.641223 -0.479749
4     E -1.434301 -1.385836 -0.031115 -1.088052

In [151]:
df['new']=['USA','Ind','China','Sri Lanka','Bangladesh']

In [152]:
df

W         X         Y         Z         new
A -1.534740  1.060125  0.044443 -0.528856         USA
B -0.087593  0.919276 -0.073113  0.294783         Ind
C -2.023998 -1.549054  0.268636  1.020451       China
D -1.457864 -0.038593  1.641223 -0.479749   Sri Lanka
E -1.434301 -1.385836 -0.031115 -1.088052  Bangladesh

In [156]:
df.set_index('new',drop=True,inplace=True)

In [157]:
df

W         X         Y         Z
new                                               
USA        -1.534740  1.060125  0.044443 -0.528856
Ind        -0.087593  0.919276 -0.073113  0.294783
China      -2.023998 -1.549054  0.268636  1.020451
Sri Lanka  -1.457864 -0.038593  1.641223 -0.479749
Bangladesh -1.434301 -1.385836 -0.031115 -1.088052

In [158]:
np.nan

nan

In [159]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [160]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [173]:
df.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C]
Index: []

In [162]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [176]:
df.fillna(value="Krish",axis=1)

A      B  C
0      1      5  1
1      2  Krish  2
2  Krish  Krish  3

In [177]:
df['A'].fillna(df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [200]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Profit':[50,100,300,120,243,350],
       'Sales':[200,120,340,124,243,350]
       }

In [201]:
df = pd.DataFrame(data)

In [202]:
df

Company   Person  Profit  Sales
0    GOOG      Sam      50    200
1    GOOG  Charlie     100    120
2    MSFT      Amy     300    340
3    MSFT  Vanessa     120    124
4      FB     Carl     243    243
5      FB    Sarah     350    350

In [203]:
com_group=df.groupby('Company')

In [182]:
com_group

In [183]:
com_group.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [185]:
com_group.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [206]:
com_group.min()

Person  Profit  Sales
Company                        
FB          Carl     243    243
GOOG     Charlie      50    120
MSFT         Amy     120    124

In [208]:
com_group.describe()

Profit                                                         Sales  \
         count   mean         std    min     25%    50%     75%    max count   
Company                                                                        
FB         2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0   2.0   
GOOG       2.0   75.0   35.355339   50.0   62.50   75.0   87.50  100.0   2.0   
MSFT       2.0  210.0  127.279221  120.0  165.00  210.0  255.00  300.0   2.0   

                                                                 
          mean         std    min     25%    50%     75%    max  
Company                                                          
FB       296.5   75.660426  243.0  269.75  296.5  323.25  350.0  
GOOG     160.0   56.568542  120.0  140.00  160.0  180.00  200.0  
MSFT     232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [209]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [210]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [211]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [216]:
pd.concat([df1,df2,df3],join='inner')

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [217]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']}) 

In [218]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [219]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [221]:
pd.merge(left,right,how='left',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [222]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [226]:
pd.merge(left, right,how='right',on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [228]:
df=pd.read_csv('example')

In [229]:
df.to

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [232]:
df1=pd.read_excel('Excel_Sample.xls',sheetname='Sheet1')

ImportError: Install xlrd >= 0.9.0 for Excel support

In [233]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

ImportError: lxml not found, please install it