In [3]:
import numpy as np

In [4]:
myList=[1,2,3]
arr=np.array(myList)

In [5]:
arr.shape

(3,)

In [6]:
myList=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(myList)

In [8]:
arr.shape


(3, 3)

In [9]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr=np.arange(10)

In [13]:
arr.shape

(10,)

In [14]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
#Identity Matrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
# random array creation with random elements
np.random.rand(4)

array([0.94911167, 0.2525479 , 0.18549351, 0.1255299 ])

In [34]:
np.random.rand(4,4)

array([[0.81273154, 0.43171784, 0.99008631, 0.40752265],
       [0.89666792, 0.78853758, 0.20084942, 0.49050557],
       [0.55455996, 0.41620874, 0.29185247, 0.438492  ],
       [0.8848399 , 0.4253063 , 0.13327392, 0.05848777]])

In [31]:
# Gaussian Distribution/Normal Distribution
#  First Standard deviation=68% , second SD =95%, third SD+ 99% in Gaussian Distribution/Normal Distribution

In [32]:
#Standard Noraml Distribution
#Standard Noraml Distribution mean(mu)=0 and SD(sigma)=1     formula is  (x-mu)/sigma

In [33]:
# standardn normal distributioon random array
np.random.randn(4,4)

array([[-0.19930741,  0.16318553, -0.36376627,  0.38183706],
       [-0.52988888,  0.12686772,  1.5895977 ,  1.44975892],
       [ 1.48362668,  1.526092  ,  0.24132216, -0.49348703],
       [ 0.24228794, -0.48591236, -0.39768787, -0.71763476]])

In [37]:
np.random.randint(1,86)

53

In [38]:
np.random.randint(1,86,15)

array([71, 76, 74, 10, 20, 12,  1, 12, 44, 58, 67, 46, 79, 62, 57])

In [39]:

arr.min()

0

In [40]:
arr.max()

9

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# index of the minimum value
arr.argmin()

0

In [43]:
arr.argmax()

9

In [44]:
arr_copy=arr.copy()


In [45]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr_copy[1:5]=57

In [47]:
arr_copy

array([ 0, 57, 57, 57, 57,  5,  6,  7,  8,  9])

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr_copy=arr[3:6].copy()

In [53]:
arr_copy

array([3, 4, 5])

In [55]:
array_2d=np.array(([5,10,2],[4,52,5],[3,2,6]))

In [70]:
array_2d[1:,:2]

array([[ 4, 52],
       [ 3,  2]])

In [71]:
array_2d

array([[ 5, 10,  2],
       [ 4, 52,  5],
       [ 3,  2,  6]])

In [75]:
array_2d[:,2:]

array([[2],
       [5],
       [6]])

In [83]:
array_2d[1:]

array([[ 4, 52,  5],
       [ 3,  2,  6]])

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [86]:
arr[arr>5]

array([6, 7, 8, 9])

In [88]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [90]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])